### ISSUE TITLE
Feature/ipv6/Wireguard tests are failing on GKE

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-gke#212] opened 2021-11-12 11:30 UTC
### Build
https://github.com/networkservicemesh/integration-k8s-gke/runs/4180847086?check_suite_focus=true

### Logs
[logs-624.zip](https://github.com/networkservicemesh/integration-k8s-gke/files/7527205/logs-624.zip)

**Comment by glazychev-art** [comment] 2021-11-17 06:32
Some information:
- Problem only with `ipv6` remote kernel cases (i.e `Memif2Wiregurad2Kernel`, `Kernel2Wiregurad2Memif`, `Kernel2Wiregurad2Kernel`)
- Error comes from `netlink.NeighSet` - [Link](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/kernel/kernelvethpair/ipneighbor/common.go#L127).  error - `invalid argument`
- Local cases work fine
- `Ipv4` cases work fine
- If we add ipneighbor manually on endpoint or client (**_not_** from forwarder) - all work fine.
- Kind cluster with `kernelvethpair` works fine
- **_It depends on GKE_** `--cluster-version`. The latest stable for us - `1.20.10-gke.301`. The next - `1.20.10-gke.1600` - is not working
- The latest logs are here (see `TestRunFeatureSuite/TestKernel2Wireguard2Kernel`)  - https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/1466709682

**Comment by denis-tingaikin** [comment] 2021-11-22 15:23
Fixed by https://github.com/networkservicemesh/integration-k8s-gke/pull/213

The root cause will be considered in https://github.com/networkservicemesh/integration-k8s-gke/issues/215

**Closed by denis-tingaikin** 2021-11-22 15:23 UTC
Labels: bug
